version: 2
jobs :
  build:
    working_directory: ~/
    steps:
      - checkout
      - restore_cache:
          key: spring5-recipe-app-{{ checksum  "pom.xml" }}
      - run: mvn package

      - store_test_results:
          - path: src/test-results
      - store_artifacts:
          - path: target/spring5-recipe-app-0.0.1-SNAPSHOT.jar
